<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="assets/img/logo.png" type="image/ico" />
    <link rel="stylesheet" href="assets/styles/css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zain:ital,wght@0,200;0,300;0,400;0,700;0,800;0,900;1,300;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer" />
    <title>SplitZ</title>
</head>

<body>
    <?php
    if (isset($_SESSION['username'])) {
        require "templates/header.phtml";
    ?>
        <main>
            <?php require "templates/$template.phtml"; ?>
        </main>
    <?php
        require "templates/footer.phtml";
    } else {
        require "templates/header-void.phtml";
    ?>
        <main>
            <?php require "templates/$template.phtml"; ?>
        </main>
    <?php
        require "templates/footer-void.phtml";
    }
    ?>
    <script type="module" src="assets/js/app.js"></script>
</body>

</html>