<section>
    <form class="form-container" action="index.php?route=check-reset-password" method="POST">
        <?php if ($_SESSION['csrf_token']) { ?>
            <input type="hidden" id="csrf_token" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>">
        <?php } ?>
        <h1>Réinitialisation de mot de passe</h1>

        <label for="email">Email :</label>
        <input type="email" id="email" name="email" required>

        <label for="new-password">Nouveau mot de passe :</label>
        <input type="password" id="new-password" name="new-password" required>

        <label for="confirm-password">Confirmer nouveau mot de passe :</label>
        <input type="password" id="confirm-password" name="confirm-password" required>

        <button class="button" type="submit">Réinitialiser mot de passe</button>
    </form>
</section>