<h1>Liste des contacts</h1>
<form method="POST" action="index.php?route=search-contact" class="container-align">
    <input type="text" id="search-bar" name="search-bar">
    <button type="submit" id="search-button">
        <i class="fas fa-search"></i>
    </button>
</form>
<section>
    <table>
        <thead>
            <tr>
                <th colspan="2">Utilisateurs</th>
            </tr>
        </thead>
        <tbody>
        <?php if (!empty($contacts)) {
                foreach ($contacts as $contact) { ?>
                    <tr>
                        <td>
                            <?= htmlspecialchars($contact['username'], ENT_QUOTES, 'UTF-8') ?>
                        </td>
                        <td>
                            <form method="POST" action="index.php?route=delete-contact&id=<?= htmlspecialchars($contact['id'], ENT_QUOTES, 'UTF-8') ?>">
                                <input type="hidden" name="identifier" value="<?= htmlspecialchars($contact['username'], ENT_QUOTES, 'UTF-8') ?>">
                                <input type="hidden" id="csrf_token" name="csrf_token" value="<?= $_SESSION['csrf_token']; ?>">
                                <button class="close-button" type="submit">
                                    <i class="fas fa-times close-button-icon"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                <?php }
                } else { ?>
                <tr>
                    <td colspan="2">Aucun contact trouvé</td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <form class="form-button" method="POST" action="index.php?route=search-contact">
    <button class="button" type="submit">
            <p class="text-icon">Ajouter un contact</p>
            <i class="fas fa-plus add-icon"></i>
        </button>
    </form>
</section>
