<h1>Liste des contacts</h1>
<form method="POST" action="index.php?route=search-contact" id="search-form" class="container-align">
    <div class="search-container">
        <select name="search-category" id="search-category" class="search-category">
            <option value="users" <?= !isset($_POST['search-category']) || $_POST['search-category'] == 'users' ? 'selected' : '' ?>>Utilisateurs</option>
            <option value="contacts" <?= isset($_POST['search-category']) && $_POST['search-category'] == 'contacts' ? 'selected' : 'selected' ?>>Contacts</option>
        </select>
        <input type="text" id="search-bar" class="search-bar" name="search-bar" value="<?= isset($_POST['search-bar']) ? htmlspecialchars($_POST['search-bar'], ENT_QUOTES, 'UTF-8') : '' ?>">
        <button type="submit" id="search-button" class="button-icon">
            <i class="fas fa-search"></i>
        </button>
    </div>
</form>
<section>
    <table>
        <thead>
            <tr>
                <th colspan="2">Utilisateurs</th>
            </tr>
        </thead>
        <tbody>
            <?php if (!empty($contacts)) {
                foreach ($contacts as $contact) { ?>
                    <tr>
                        <td>
                            <?= htmlspecialchars($contact['username'], ENT_QUOTES, 'UTF-8') ?>
                        </td>
                        <td>
                            <form method="POST" action="index.php?route=delete-contact&id=<?= htmlspecialchars($contact['id'], ENT_QUOTES, 'UTF-8') ?>">
                                <input type="hidden" name="identifier" value="<?= htmlspecialchars($contact['username'], ENT_QUOTES, 'UTF-8') ?>">
                                <input type="hidden" id="csrf_token" name="csrf_token" value="<?= $_SESSION['csrf_token']; ?>">
                                <button class="close-button" type="submit">
                                    <i class="fas fa-times close-button-icon"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                <?php }
            } else { ?>
                <tr>
                    <td colspan="2">Aucun contact trouvé</td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <form class="form-button" method="POST" action="index.php?route=search-user">
        <button class="button" type="submit">
            <p class="text-icon">Ajouter un contact</p>
            <i class="fas fa-plus add-icon"></i>
        </button>
    </form>
</section>